server:
  port: 8090
  servlet:
    context-path: /simple-ai

  compression:
    enabled: TRUE #Whether response compression is enabled. Default fasle

spring:
  application:
    name: simple-ai	

#  main:
#    web-application-type: NONE #if Web dependency is not added

  profiles:
    active: ollama