spring:
  ai:
    ollama:
      base-url: ${AI_OLLAMA_URL}
      chat:
        model: ${AI_OLLAMA_MODEL}
        options:
          temperature: ${AI_OLLAMA_TEMPRATURE}
          stream: true  # Enable streaming support

    retry:
      max-attempts: ${AI_RETRY_ATTEMPT} #Maximum number of retry attempts. default is 10
